# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_b32_wrappers", use_symbols = TRUE, package_name = "b32")

#' @usage NULL
#' @useDynLib b32, .registration = TRUE
NULL

encode_ <- function(x, alphabet, padded) .Call(wrap__encode_, x, alphabet, padded)

decode_ <- function(x, alphabet, padded) .Call(wrap__decode_, x, alphabet, padded)


# nolint end
